### PR TITLE
TLS - trying this again

### PR DESCRIPTION
**Pull request by thelonelyshammy**
This is the only way it seems to work, Shiz. All other attempts are either failing or say something about there being no differences.

image

Those are the selections I made. That is the only base fork option with your name in it and that is the only 'shizweak-server' option under Base. If this doesn't work, I'll drop the PBO on trello.

### CODE REVIEW

**Comment by shizweak** [comment]
Yep that's right, will test shortly

**Comment by thelonelyshammy** [comment]
Can you also test if AH-9s don't spawn with weird weapon loadouts after a restart? I think that either the XAH-9 (with the 20mm) will either restart with the default loadout or ALL AH-9s will restart with the WRONG loadout.

**Comment by thelonelyshammy** [comment]
Armed Choppers, other than the AH9, don't seem to be spawning with ammo.

**Comment by shizweak** [comment]
Hm, even ones you haven't changed anything on?

**Pull request closed without merging**
