### PR TITLE
Store Location Updates

### PR DESCRIPTION
**Pull request by bigape-2015**
Added an ATM to Balota Airfield
Added an ATM to Zelengorsk
Added an ATM to Gvodzno
Added a ATM to Kraznostav
Added an Gun Store to Zelengorsk
Added a General Store to Kraznostav
Moved vehicle Seller from Gvodzno to NEAF
Cleaned up the Gun Store location entries and added comment fields to all of the store classes so that we can see what they all are and to the storeOwners.sqf

### CODE REVIEW

**Comment by shizweak** [comment]
Can't see the ATM's at Bolato and Kratzonav, all others look fine

**Comment by shizweak** [comment]
Further note, it appears Gvozdno/Kraznostav ATM's are in the mission SQM twice - perhaps related to the issues!

**Comment by bigape-2015** [comment]
Ignore the last commit if you don't want the Mog extras. The fix for "Can't load mission" is inthe Fix for Markers class commits

**Comment by shizweak** [comment]
Awesome thanks, I'll merge it with Mog and see how we go

**Comment by shizweak** [comment]
Tested, all looks good, merging

**Pull request merged**
